"use strict";

try {
    let x = 10;
    // myFunction();
} catch(error) {
    console.log(error);
} finally {
    console.log("Finish errors review")
}


console.log("continue...");